name: terraform-ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: hashicorp/setup-terraform@v4.0.0
        with:
          terraform_version: "~> 1.9"

      - name: terraform fmt
        run: terraform fmt -recursive -check

      - name: terraform init
        run: terraform init -backend=false

      - name: terraform validate
        run: terraform validate

      - name: terraform test
        run: terraform test

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: tflint init
        run: tflint --init

      - name: tflint
        run: tflint --recursive
